project_id = "rogwhlgqsyasbemnovgf"

[functions.send-interview-schedule]
verify_jwt = false

[functions.send-interview-notification]
verify_jwt = false

[functions.notify-clearance-initiated]
verify_jwt = false

[functions.notify-department-approved]
verify_jwt = false

[functions.notify-clearance-complete]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-letter]
verify_jwt = false

[functions.send-letter-email]
verify_jwt = false

[functions.generate-weekly-report]
verify_jwt = false
