import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { useEmployees } from '@/hooks/useEmployees';
import { useDepartments } from '@/hooks/useDepartments';
import { useTenant } from '@/contexts/TenantContext';
import { useToast } from '@/hooks/use-toast';
import { Plus, CalendarIcon } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';

const AddEmployeeForm = () => {
  const [formData, setFormData] = useState({
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    address: '',
    position: '',
    department: '',
    branch: '',
    hire_date: '',
    salary: '',
    contract_type: 'full-time',
    contract_start_date: '',
    contract_duration_months: '12',
    emergency_contact_name: '',
    emergency_contact_phone: '',
    emergency_contact_relationship: '',
    kra_pin: '',
    shif_number: '',
    nssf_number: ''
  });
  const [contractStartDate, setContractStartDate] = useState<Date>();
  const [open, setOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [nextEmployeeNumber, setNextEmployeeNumber] = useState<string>('');
  const { tenant } = useTenant();
  const { createEmployee } = useEmployees();
  const { departments, loading: departmentsLoading } = useDepartments(tenant?.id);
  const { toast } = useToast();

  // Fetch next employee number when dialog opens
  useEffect(() => {
    if (open) {
      fetchNextEmployeeNumber();
    }
  }, [open]);

  const fetchNextEmployeeNumber = async () => {
    try {
      const { data, error } = await supabase.rpc('get_next_employee_number');
      if (error) {
        console.error('Error fetching next employee number:', error);
      } else {
        setNextEmployeeNumber(data);
      }
    } catch (error) {
      console.error('Error fetching next employee number:', error);
    }
  };

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    console.log('Form submission started');
    console.log('Form data:', formData);
    
    if (!formData.first_name || !formData.last_name || !formData.email || !formData.position || !formData.department || !formData.hire_date) {
      toast({
        title: "Validation Error",
        description: "Please fill in all required fields (First Name, Last Name, Email, Position, Department, Hire Date).",
        variant: "destructive"
      });
      return;
    }

    setSubmitting(true);
    
    try {
      if (!tenant?.id) {
        toast({
          title: "Error",
          description: "No tenant context available. Please try again.",
          variant: "destructive"
        });
        setSubmitting(false);
        return;
      }

      const employeeData = {
        employee_number: '', // Will be auto-generated by trigger
        first_name: formData.first_name,
        last_name: formData.last_name,
        email: formData.email,
        phone: formData.phone || null,
        address: formData.address || null,
        position: formData.position,
        department: formData.department,
        branch: formData.branch || null,
        hire_date: formData.hire_date,
        salary: formData.salary ? parseFloat(formData.salary) : null,
        contract_type: formData.contract_type,
        contract_start_date: contractStartDate ? format(contractStartDate, 'yyyy-MM-dd') : null,
        contract_duration_months: parseInt(formData.contract_duration_months),
        emergency_contact_name: formData.emergency_contact_name || null,
        emergency_contact_phone: formData.emergency_contact_phone || null,
        emergency_contact_relationship: formData.emergency_contact_relationship || null,
        status: 'active',
        tenant_id: tenant.id
      };

      console.log('Processed employee data:', employeeData);

      const { error } = await createEmployee(employeeData);

      if (error) {
        console.error('Employee creation error:', error);
        toast({
          title: "Error",
          description: error.message || "Failed to create employee profile. Please check all fields and try again.",
          variant: "destructive"
        });
      } else {
        toast({
          title: "Success",
          description: "Employee profile created successfully!"
        });
        
        // Reset form
        setFormData({
          first_name: '',
          last_name: '',
          email: '',
          phone: '',
          address: '',
          position: '',
          department: '',
          branch: '',
          hire_date: '',
          salary: '',
          contract_type: 'full-time',
          contract_start_date: '',
          contract_duration_months: '12',
          emergency_contact_name: '',
          emergency_contact_phone: '',
          emergency_contact_relationship: '',
          kra_pin: '',
          shif_number: '',
          nssf_number: ''
        });
        setContractStartDate(undefined);
        setOpen(false);
      }
    } catch (error) {
      console.error('Unexpected error:', error);
      toast({
        title: "Error",
        description: "An unexpected error occurred. Please try again.",
        variant: "destructive"
      });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 shadow-lg">
          <Plus className="mr-2 h-4 w-4" />
          Add Employee
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Add New Employee</DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Personal Information */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Personal Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="employee_number">Employee Number</Label>
                  <Input
                    id="employee_number"
                    value={nextEmployeeNumber}
                    disabled
                    className="bg-muted"
                    placeholder="Auto-generated"
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    This will be auto-generated when you create the employee
                  </p>
                </div>

                <div>
                  <Label htmlFor="contract_type">Contract Type</Label>
                    <Select value={formData.contract_type} onValueChange={(value) => handleInputChange('contract_type', value)}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="full-time">Full-time</SelectItem>
                        <SelectItem value="part-time">Part-time</SelectItem>
                        <SelectItem value="contract">Contract</SelectItem>
                        <SelectItem value="temporary">Temporary</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="first_name">First Name *</Label>
                    <Input
                      id="first_name"
                      value={formData.first_name}
                      onChange={(e) => handleInputChange('first_name', e.target.value)}
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="last_name">Last Name *</Label>
                    <Input
                      id="last_name"
                      value={formData.last_name}
                      onChange={(e) => handleInputChange('last_name', e.target.value)}
                      required
                    />
                  </div>
                </div>

                <div>
                  <Label htmlFor="email">Email *</Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="phone">Phone</Label>
                  <Input
                    id="phone"
                    value={formData.phone}
                    onChange={(e) => handleInputChange('phone', e.target.value)}
                  />
                </div>

                <div>
                  <Label htmlFor="address">Address</Label>
                  <Textarea
                    id="address"
                    value={formData.address}
                    onChange={(e) => handleInputChange('address', e.target.value)}
                    rows={3}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Employment Information */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Employment Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="position">Position *</Label>
                  <Input
                    id="position"
                    value={formData.position}
                    onChange={(e) => handleInputChange('position', e.target.value)}
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="department">Department *</Label>
                  <Select value={formData.department} onValueChange={(value) => handleInputChange('department', value)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select department" />
                    </SelectTrigger>
                    <SelectContent>
                      {departmentsLoading ? (
                        <div className="p-2 text-sm text-muted-foreground">Loading departments...</div>
                      ) : departments.length === 0 ? (
                        <div className="p-2 text-sm text-muted-foreground">No departments found</div>
                      ) : (
                        departments.map((dept) => (
                          <SelectItem key={dept.id} value={dept.name}>{dept.name}</SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="branch">Branch</Label>
                  <Select value={formData.branch} onValueChange={(value) => handleInputChange('branch', value)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select branch" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="langata">Langata</SelectItem>
                      <SelectItem value="sabaki">Sabaki</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="hire_date">Hire Date *</Label>
                  <Input
                    id="hire_date"
                    type="date"
                    value={formData.hire_date}
                    onChange={(e) => handleInputChange('hire_date', e.target.value)}
                    required
                  />
                </div>

                <div>
                  <Label>Contract Start Date</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={cn(
                          "w-full justify-start text-left font-normal",
                          !contractStartDate && "text-muted-foreground"
                        )}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {contractStartDate ? format(contractStartDate, "PPP") : "Pick a date"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={contractStartDate}
                        onSelect={setContractStartDate}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <div>
                  <Label htmlFor="contract_duration_months">Contract Duration (Months)</Label>
                  <Input
                    id="contract_duration_months"
                    type="number"
                    value={formData.contract_duration_months}
                    onChange={(e) => handleInputChange('contract_duration_months', e.target.value)}
                    placeholder="12"
                  />
                </div>

                <div>
                  <Label htmlFor="salary">Salary</Label>
                  <Input
                    id="salary"
                    type="number"
                    step="0.01"
                    value={formData.salary}
                    onChange={(e) => handleInputChange('salary', e.target.value)}
                    placeholder="50000.00"
                  />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Statutory Compliance */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Statutory Compliance</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <Label htmlFor="kra_pin">KRA PIN</Label>
                  <Input
                    id="kra_pin"
                    value={formData.kra_pin}
                    onChange={(e) => handleInputChange('kra_pin', e.target.value)}
                    placeholder="A000000000X"
                  />
                </div>
                <div>
                  <Label htmlFor="shif_number">SHIF Number</Label>
                  <Input
                    id="shif_number"
                    value={formData.shif_number}
                    onChange={(e) => handleInputChange('shif_number', e.target.value)}
                    placeholder="SHIF number"
                  />
                </div>
                <div>
                  <Label htmlFor="nssf_number">NSSF Number</Label>
                  <Input
                    id="nssf_number"
                    value={formData.nssf_number}
                    onChange={(e) => handleInputChange('nssf_number', e.target.value)}
                    placeholder="NSSF number"
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Emergency Contact */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Emergency Contact</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <Label htmlFor="emergency_contact_name">Contact Name</Label>
                  <Input
                    id="emergency_contact_name"
                    value={formData.emergency_contact_name}
                    onChange={(e) => handleInputChange('emergency_contact_name', e.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="emergency_contact_relationship">Relationship</Label>
                  <Input
                    id="emergency_contact_relationship"
                    value={formData.emergency_contact_relationship}
                    onChange={(e) => handleInputChange('emergency_contact_relationship', e.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="emergency_contact_phone">Phone Number</Label>
                  <Input
                    id="emergency_contact_phone"
                    value={formData.emergency_contact_phone}
                    onChange={(e) => handleInputChange('emergency_contact_phone', e.target.value)}
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="flex justify-end space-x-4">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button 
              type="submit" 
              disabled={submitting}
              className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800"
            >
              {submitting ? 'Creating...' : 'Create Employee'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default AddEmployeeForm;
