// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rogwhlgqsyasbemnovgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZ3dobGdxc3lhc2JlbW5vdmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjE4NzQsImV4cCI6MjA2NTczNzg3NH0.jKAg3ennqyY6B57nh_r6q-9QguC0RZXGgbkhA3MZzC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);